language: php
sudo: false
php:
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml --exclude=InterNations.Naming.NamespaceName,Generic.PHP.RequireStrictTypes ./src/
  - vendor/bin/phpunit
