language: php
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer install

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml --exclude=InterNations.Naming.NamespaceName,Generic.PHP.RequireStrictTypes ./src/ ; fi'
  - vendor/bin/phpunit
